theme: jekyll-theme-cayman
title: Deep Learning Decoded's Homepage!
description: For those who just couldn't make it through Goodfellow et al
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
